### ISSUE TITLE
NetCDF: Invalid argument

### ISSUE THREAD

**Issue by ldecicco-USGS** [mjwoods/RNetCDF#72] opened 2019-10-23 19:55 UTC
I'm trying to run the following code:
```r
  nc_file <- "https://cida.usgs.gov/thredds/dodsC/stageiv_combined"
  RNetCDF::open.nc(nc_file)
Error in RNetCDF::open.nc(nc_file) : NetCDF: Invalid argument
```
I'm on Windows 10, and my Mac co-workers are able to do this no problem.

When I go in the Terminal:
```
ncdump --version
netcdf library version 4.7.2 of Oct 22 2019 12:06:21
```

Can you recommend anything to allow me to use an OPeNDAP URL?

**Comment by dblodgett-usgs** [comment] 2019-10-24 12:17
Could this be related to the discussion in the comments of PR #13? Was chatting with @ldecicco-USGS offline and she reported that using the latest NetCDF-4+DAP 64-bit installed from here: https://www.unidata.ucar.edu/downloads/netcdf/index.jsp

She is seeing:
```
$ ncdump -sh https://cida.usgs.gov/thredds/dodsC/stageiv_combined
curl error details:
C:\Program Files\netCDF 4.7.2\bin\ncdump.exe: https://cida.usgs.gov
/thredds/dodsC/stageiv_combined: https://cida.usgs.gov/thredds/dods
C/stageiv_combined: NetCDF: I/O failure
```

Which indicates that this may actually be related to this version of NetCDF not working with DAP on windows?

**Comment by jeroen** [comment] 2019-10-24 21:27
DAP only works on 64 bit. Are you using the legacy 32bit windows perhaps?

**Comment by ldecicco-USGS** [comment] 2019-10-24 21:33
Nope, 64-bit:
```r
> devtools::session_info()
- Session info ----------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Chicago             
 date     2019-10-24                  

- Packages --------------------------------------------------------------------------------
 package     * version    date       lib source                                    
 abind       * 1.4-5      2016-07-21 [1] CRAN (R 3.6.0)                            
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                            
 backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                            
 callr         3.3.2      2019-09-22 [1] CRAN (R 3.6.1)                            
 class         7.3-15     2019-01-01 [2] CRAN (R 3.6.1)                            
 classInt      0.4-2      2019-10-17 [1] CRAN (R 3.6.1)                            
 cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.0)                            
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.2)                            
 data.table    1.12.6     2019-10-18 [1] CRAN (R 3.6.1)                            
 DBI           1.0.0      2018-05-02 [1] CRAN (R 3.6.0)                            
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.2)                            
 devtools      2.2.1      2019-09-24 [1] CRAN (R 3.6.1)                            
 digest        0.6.21     2019-09-20 [1] CRAN (R 3.6.1)                            
 dplyr         0.8.3      2019-07-04 [1] CRAN (R 3.6.1)                            
 e1071         1.7-2      2019-06-05 [1] CRAN (R 3.6.0)                            
 ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)                            
 fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                            
 glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                            
 intersectr  * 0.0.2      2019-09-30 [1] Github (dblodgett-usgs/intersectr@bc25780)
 KernSmooth    2.23-15    2015-06-29 [2] CRAN (R 3.6.1)                            
 lwgeom        0.1-7      2019-05-06 [1] CRAN (R 3.6.1)                            
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.2)                            
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.2)                            
 ncmeta      * 0.2.0      2019-10-22 [1] CRAN (R 3.6.1)                            
 packrat       0.5.0      2018-11-14 [1] CRAN (R 3.5.2)                            
 pillar        1.4.2      2019-06-29 [1] CRAN (R 3.6.0)                            
 pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)                            
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.1)                            
 pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.2)                            
 prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.2)                            
 processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.1)                            
 ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.2)                            
 purrr         0.3.3      2019-10-18 [1] CRAN (R 3.6.1)                            
 R6            2.4.0      2019-02-14 [1] CRAN (R 3.6.0)                            
 Rcpp          1.0.2      2019-07-25 [1] CRAN (R 3.6.1)                            
 remotes       2.1.0.9000 2019-09-26 [1] Github (robertdj/remotes@e2743d8)         
 rlang         0.4.0      2019-06-25 [1] CRAN (R 3.6.0)                            
 RNetCDF     * 2.1-1      2019-10-20 [1] CRAN (R 3.6.1)                            
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.2)                            
 rstudioapi    0.10       2019-03-19 [1] CRAN (R 3.6.0)                            
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.2)                            
 sf          * 0.8-0      2019-09-17 [1] CRAN (R 3.6.1)                            
 stars       * 0.4-0      2019-10-10 [1] CRAN (R 3.6.1)                            
 testthat      2.2.1      2019-07-25 [1] CRAN (R 3.6.1)                            
 tibble        2.1.3      2019-06-06 [1] CRAN (R 3.6.0)                            
 tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.5.2)                            
 units         0.6-5      2019-10-08 [1] CRAN (R 3.6.1)                            
 usethis       1.5.1      2019-07-04 [1] CRAN (R 3.6.1)                            
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.2)                            

[1] C:/Users/ldecicco/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.1/library
```

**Comment by mjwoods** [comment] 2019-10-25 02:45
I was interested to find that RNetCDF does work with some OpenDAP URLs on Windows x64. For example:

```
url <- http://coastwatch.pfeg.noaa.gov/erddap/griddap/erdQSwind3day
library(RNetCDF)
nc <- open.nc(url)
print.nc(nc)
```

Maybe our Windows package for RNetCDF is having trouble with https, as opposed to http.

@jeroen - do you know if the libcurl.a in https://github.com/rwinlib/netcdf is built with openssl support? If so, does it need to include other libraries, as in https://github.com/rwinlib/libcurl ?

**Comment by ldecicco-USGS** [comment] 2019-10-25 03:27
Just to confirm...that http works for me too!

**Comment by mjwoods** [comment] 2019-10-25 07:47
I also tested the `ncdump` command available from Cygwin. It worked with the troublesome URL reported by @ldecicco-USGS , that is:

```
ncdump -hs  https://cida.usgs.gov/thredds/dodsC/stageiv_combined
```

This shows that NetCDF+OpenDAP can work properly on Windows. We just need to figure out how to build it without Cygwin.

**Comment by mjwoods** [comment] 2019-10-26 02:34
I built netcdf-4.7.2 and hdf5-1.10.5 on Windows with msys2. The resulting `ncdump` command worked, even using the URL from @ldecicco-USGS .

I doubt that we can use the netcdf library as I built it, because it requires the msys-curl DLL provided by msys2. But maybe our main problem is this - we need a curl library with all of the bells and whistles, including openssl certificates and various cryptographic packages.

**Comment by mjwoods** [comment] 2019-10-29 08:44
I downloaded and tested several versions of the official Windows builds of netcdf from Unidata. Versions tested included 4.7.2, 4.6.3, 4.4.1.1, 4.3.3.1. So far, none of them worked with the URL https://cida.usgs.gov/thredds/dodsC/stageiv_combined . Older versions gave the following error message:

```
CURL Error: Unsupported protocol
curl error details:
.\ncdump.exe: https://cida.usgs.gov/thredds/dodsC/stageiv_combined: NetCDF: I/O failure
```

**Comment by dblodgett-usgs** [comment] 2019-10-29 11:52
Can someone with one of these windows installs verify that OPeNDAP works or doesn't with other dap services? The one in question is a bit of an edge case.
e.g. `https://cida.usgs.gov/thredds/dodsC/prism_v2` 

or 

`https://data.nodc.noaa.gov/thredds/dodsC/livnehmodel/1950/Fluxes_Livneh_NAmerExt_15Oct2014.195001.nc`

**Comment by mdsumner** [comment] 2019-10-29 11:58
Yes I wanted to ask that also that we also get  tests of this for ncdf4, RNetCDF, stars::read_stars and from OSGeo4W and/or QGIS. I just don't have as easy access to Windows as I once did. I expect ncdf4 and RNetCDF are equivalent nowadays though, given that the same toolchain is used (as of last week or so).

**Comment by dblodgett-usgs** [comment] 2019-10-29 12:03
Not to belabor the testing, but just to get a baseline, it would be nice to know if the old RNetCDF worked with these -- I was under the impression that the answer was yes.

**Comment by dblodgett-usgs** [comment] 2019-10-29 16:20
Thanks. That indicates that there is something strange with the stageiv_combined OPeNDAP service that is causing the NetCDF library to throw curl errors. I'll get with @ldecicco-USGS and see if we can narrow down what's happening. The two tests above show that it isn't an ssl issue and isn't specific to the cida thredds instance.

**Comment by mjwoods** [comment] 2019-11-04 08:49
Hi @dblodgett-usgs , I just tested RNetCDF_1.9-1 on R-3.6.1 for win64, with the following results:

```
> x <- RNetCDF::open.nc("https://cida.usgs.gov/thredds/dodsC/prism_v2")
> str(x)
 'NetCDF' num 196608
> x <- RNetCDF::open.nc("https://cida.usgs.gov/thredds/dodsC/prism_v2")
> str(x)
 'NetCDF' num 196608
> z <- RNetCDF::open.nc("https://cida.usgs.gov/thredds/dodsC/stageiv_combined")
Error: NetCDF: Invalid argument
```

So the "stageiv_combined" URL fails even with the old RNetCDF. This problem does seem to be caused by something in libnetcdf or its dependencies (on Windows).

**Comment by dblodgett-usgs** [comment] 2019-11-04 21:44
OK. I'd say close this and we'll look at it on the stageiv side and see if we can fix things there.

**Comment by jeroen** [comment] 2019-11-04 22:02
FYI from my experiences, netcdf is extremely buggy on Windows. I tried different versions and they freeze or crash in different places.

Netcdf 4.4.1.1 would always crash when using DAP on Windows 32 bit, so therefore we ended up only enabling DAP on 64 bit Windows. 

Last month I tried with netcdf 4.7.1 and it now just always freezes on Windows for any DAP server, both in 32 bit and 64 bit Windows. I'm afraid the netcdf authors don't really test much on Windows.

**Comment by dblodgett-usgs** [comment] 2019-11-05 04:46
I've had very good luck reporting issues to them and getting them fixed. Did you report any of these issues to Unidata?

**Comment by mjwoods** [comment] 2020-07-27 01:37
Hi @jeroen , now that Rtools40 for Windows is based on reasonably up-to-date MinGW, it should be possible to release RNetCDF packages built with recent MinGW versions of the NetCDF library and other dependencies. Do you know if there are any plans to provide a comprehensive set of MinGW packages on win-builder? If they are available already, do you know how R packages should use them?

**Comment by jeroen** [comment] 2020-07-27 07:47
Right now, CRAN still has to support both R 3.6 and R 4.0 so you cannot fully rely on rtools40 yet. Maybe after the release of R 4.1 this will be possible.

You can see and update the packages here: https://github.com/r-windows/rtools-packages

**Comment by mjwoods** [comment] 2020-07-29 22:53
Thanks @jeroen , I see that netcdf is already in the list of packages. Are those packages installed on win-builder? If so, how could I use them with R>4?

**Comment by mjwoods** [comment] 2021-08-16 05:42
Good news! The upcoming RNetCDF-2.5 seems to resolve this issue, by using the latest build of netcdf-4.7.4 in rtools40/rwinlib. Both the 64-bit and 32-bit packages have been tested in R-4.1.0 on Windows 10, with the following results:

```
> library(RNetCDF)
> nc <- open.nc("https://cida.usgs.gov/thredds/dodsC/stageiv_combined")
> print.nc(nc)
netcdf classic {
dimensions:
        time = 171792 ;
        time_bounds_1 = 2 ;
        x = 1121 ;
        y = 881 ;
variables:
        NC_FLOAT lon(y, x) ;
                NC_CHAR lon:units = "degrees_east" ;
                NC_INT lon:_ChunkSizes = 75, 60 ;
                NC_CHAR lon:_CoordinateAxisType = "Lon" ;
        NC_FLOAT lat(y, x) ;
                NC_CHAR lat:units = "degrees_north" ;
                NC_INT lat:_ChunkSizes = 75, 60 ;
                NC_CHAR lat:_CoordinateAxisType = "Lat" ;
        NC_DOUBLE time(time) ;
                NC_CHAR time:units = "Hour since 2001-12-31T23:00:00Z" ;
                NC_CHAR time:standard_name = "time" ;
                NC_CHAR time:long_name = "GRIB forecast or observation time" ;
                NC_CHAR time:calendar = "proleptic_gregorian" ;
                NC_CHAR time:bounds = "time_bounds" ;
                NC_CHAR time:_CoordinateAxisType = "Time" ;
                NC_INT time:_ChunkSizes = 1000 ;
        NC_FLOAT Total_precipitation_surface_1_Hour_Accumulation(x, y, time) ;
                NC_CHAR Total_precipitation_surface_1_Hour_Accumulation:long_name = "Total precipitation (1_Hour Accumulation) @ Ground or water surface" ;
                NC_CHAR Total_precipitation_surface_1_Hour_Accumulation:description = "Total precipitation" ;
                NC_FLOAT Total_precipitation_surface_1_Hour_Accumulation:missing_value = NaN ;
                NC_CHAR Total_precipitation_surface_1_Hour_Accumulation:coordinates = "time lat lon" ;
                NC_CHAR Total_precipitation_surface_1_Hour_Accumulation:units = "kg m^-2" ;
                NC_INT Total_precipitation_surface_1_Hour_Accumulation:_ChunkSizes = 1, 60, 75 ;
                NC_CHAR Total_precipitation_surface_1_Hour_Accumulation:standard_name = "precipitation_amount" ;
                NC_FLOAT Total_precipitation_surface_1_Hour_Accumulation:_FillValue = NaN ;
                NC_CHAR Total_precipitation_surface_1_Hour_Accumulation:cell_methods = "time: sum (interval: 1 hr)" ;
        NC_DOUBLE time_bounds(time_bounds_1, time) ;
                NC_CHAR time_bounds:units = "Hour since 2001-12-31T23:00:00Z" ;
                NC_CHAR time_bounds:long_name = "bounds for time" ;
                NC_INT time_bounds:_ChunkSizes = 1, 2 ;

// global attributes:
                NC_CHAR :Originating_or_generating_Center = "US National Weather Service, National Centres for Environmental Prediction (NCEP)" ;
                NC_CHAR :Originating_or_generating_Subcenter = "Environmental Modeling Center" ;
                NC_CHAR :Generating_process_or_model = "River Forecast Center Quantitative Precipitation estimate mosaic generated by NCEP" ;
                NC_CHAR :Conventions = "CF-1.4" ;
                NC_CHAR :history = "Aggregated from NCEP Stage IV Analysis by dblodgett@usgs.gov 2016-01-01" ;
                NC_CHAR :featureType = "GRID" ;
                NC_CHAR :_CoordSysBuilder = "ucar.nc2.dataset.conv.CF1Convention" ;
                NC_CHAR :Metadata_Conventions = "Unidata Dataset Discovery v1.0" ;
                NC_CHAR :title = "United States Stage IV Quantitative Precipitation Archive" ;
                NC_CHAR :summary = "Mosaicked into a national product at NCEP, from the regional hourly multi-sensor (radar+gauges) precipitation analyses produced by the 12 River Forecast Centers over CONUS. Some manual QC done at the RFCs.  The Stage II/IV job is run at 33min past the top of each hour. Hourly Stage IV is re-made hourly (if there is new input after valid time for the next 23 hours, then again at 1/3/5/7 days after valid time.  Source: http://www.emc.ncep.noaa.gov/mmb/ylin/pcpanl/stage4/ Note: This dataset is not truely national. Some RFCs do not produce hourly precip estimates and others may not be present in the dataset. Please review the NCEP documentation for more information." ;
                NC_CHAR :keywords = "Atmosphere > Precipitation > Precipitation Amount   Atmosphere > Precipitation > Rain" ;
                NC_CHAR :keywords_vocabulary = "GCMD Science Keywords" ;
                NC_CHAR :id = " stageiv" ;
                NC_CHAR :naming_authority = "cida.usgs.gov" ;
                NC_CHAR :cdm_data_type = "Grid" ;
                NC_CHAR :date_created = "ongoing" ;
                NC_CHAR :institution = "National Center for Environmental Prediction" ;
                NC_CHAR :project = "Various" ;
                NC_CHAR :processing_level = "Aggregated .grib archive from the NCEP. The original Hydrologic Rainfall Analysis Projection grid cell locations redefined by unprojecting grid cell locations using spherical earth projection algorithms.    The cell lat/lon locations should be interpreted as being on a modern geotetic datum. This transformation is needed because the original grid cell location's lat/lon values were on a geodetic datum but were assumed to be on a spherical datum.    See: https://pubs.usgs.gov/fs/2013/3035/pdf/fs2013-3035.pdf for more information. Note that this publication reverences the National Precipitation Verification Unit.   The data represented here are aggregated from the same source as the National Precipitation Verification Unit used prior to being shut down. Data processing notes can be found here: http://www.emc.ncep.noaa.gov/mmb/ylin/pcpanl/" ;
                NC_CHAR :acknowledgement = "Data originated at the National Center for Environmental Prediction: http://www.emc.ncep.noaa.gov/mmb/ylin/pcpanl/stage4/" ;
                NC_CHAR :geospatial_lat_min = "24" ;
                NC_CHAR :geospatial_lat_max = "53" ;
                NC_CHAR :geospatial_lon_min = "-125" ;
                NC_CHAR :geospatial_lon_max = "-66" ;
                NC_CHAR :time_coverage_start = "2002-01-01T00:00:00Z" ;
                NC_CHAR :time_coverage_end = "present" ;
                NC_CHAR :license = "Freely available" ;
                NC_CHAR :contributor_name = "Center for Integrated Data Analytics" ;
                NC_CHAR :contributor_role = "Aggregation and Serving via THREDDS" ;
                NC_CHAR :geospatial_lat_units = "km" ;
                NC_CHAR :geospatial_lat_resolution = "4" ;
                NC_CHAR :geospatial_lon_units = "km" ;
                NC_CHAR :geospatial_lon_resolution = "4" ;
                NC_CHAR :geospatial_vertical_units = "km" ;
}
> data <- var.get.nc(nc, "Total_precipitation_surface_1_Hour_Accumulation", start=c(1,1,1000), count=c(NA,NA,2))
> dim(data)
[1] 1121  881    2
```

**Closed** 2022-01-10 23:06 UTC

**Comment by seanhardison1** [comment] 2024-04-05 21:20
Anyone still having issues with this? I recently switched to windows from mac and can no longer read `.nc` files off of this thredds server.

````
>   url <- "https://data.pmel.noaa.gov/aclim/thredds/fileServer/B10K-K20_CORECFS/Level2/2015-2019/B10K-K20_CORECFS_2015-2019_average_temp_integrated.nc"
>   download.file(url,destfile = "./test.nc")
trying URL 'https://data.pmel.noaa.gov/aclim/thredds/fileServer/B10K-K20_CORECFS/Level2/2015-2019/B10K-K20_CORECFS_2015-2019_average_temp_integrated.nc'
Content type 'application/x-netcdf' length 98061812 bytes (93.5 MB)
downloaded 93.5 MB

> 
>   file.exists("./test.nc")
[1] TRUE
> 
>   RNetCDF::open.nc("./test.nc") #fails
Error in RNetCDF::open.nc("./test.nc") : Invalid argument
>   ncdf4::nc_open("./test.nc") #fails
Error in R_nc4_open: Invalid argument
Error in ncdf4::nc_open("./test.nc") : 
  Error in nc_open trying to open file ./test.nc (return_on_error= FALSE )
>   stars::read_ncdf("./test.nc") #fails
Error in RNetCDF::open.nc(x) : Invalid argument
````

**Comment by seanhardison1** [comment] 2024-04-05 21:57
Problem solved! Including `mode = "wb"` in `download(...)` seems to fix this.

````
  library(raster)

  url <- "https://data.pmel.noaa.gov/aclim/thredds/fileServer/B10K-K20_CORECFS/Level2/2015-2019/B10K-K20_CORECFS_2015-2019_average_temp_integrated.nc"
  download.file(url,destfile = "./test.nc", mode = "wb")

  file.exists("./test.nc")
  plot(raster::raster("./test.nc"))
  RNetCDF::open.nc("./test.nc") #works
````

**Comment by mjwoods** [comment] 2024-04-07 01:30
Hi @seanhardison1 , you can also avoid downloading the whole dataset by using OPeNDAP, which is supported by the thredds server. It just involves using a slightly different URL in this case. For example:

```
# View the metadata:
library(RNetCDF)
url <- "https://data.pmel.noaa.gov/aclim/thredds/dodsC/B10K-K20_CORECFS/Level2/2015-2019/B10K-K20_CORECFS_2015-2019_average_temp_integrated.nc"
nc <- open.nc(url)
print.nc(nc)

# Download a variable into a raster and plot it:
library(stars)
library(ggplot2)
# This uses RNetCDF under the hood:
rast <- stars::read_ncdf(url, var="temp")
ggplot() + geom_stars(data=rast, downsample=5)
```

**Comment by seanhardison1** [comment] 2024-04-08 15:12
that is extremely helpful! thank you
